import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Contactnav from "@/components/Contactnav";
import CartProvider from "@/context/CartContext";
import WishlistProvider from "@/context/WishlistContext";
// import { WishlistProvider } from "@/context/WishlistContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bandage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Contactnav />
        <CartProvider>
          <WishlistProvider>
            <main className="bg-[#FFFFFF]">
              <Navbar />
              {children}
            </main>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
